version: '3.8'

services:
    cluckoo_nginx:
        image: nginx:alpine
        container_name: cluckoo_laravel
        restart: unless-stopped
        tty: true
        ports:
            - "3001:3001"
        depends_on:
            - cluckoo_service
        volumes:
            - ./:/var/www/cluckoo_laravel
            - ./.docker/nginx/conf/local:/etc/nginx/conf.d
            - ./.docker/nginx/log:/var/log/nginx
        networks:
            - network

    cluckoo_service:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: cluckoo_service
        restart: unless-stopped
        tty: true
        env_file:
            - .//.env
        ports:
            - "5001:5001"
        volumes:
            - ./:/var/www/cluckoo_laravel
            - ./.docker/php/local.ini:/usr/local/etc/php/local.ini
        networks:
            - network
            - dcoderz_network
networks:
    network:
        driver: bridge
    dcoderz_network:
        external: true

# volumes:
#     database-volume: